### ISSUE TITLE
TypeError: put() takes at most 4 arguments (5 given)

### ISSUE THREAD

**Issue by shirk3y** [istresearch/ist-memex-api#3]
A strange error encountered while creating new log entry:

```python
"POST /logs HTTP/1.1" 500 13604
http://127.0.0.1:8000/logs
Traceback (most recent call last):
  File "/Users/shirkey/.virtualenvs/memex-api/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shirkey/.virtualenvs/memex-api/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/shirkey/.virtualenvs/memex-api/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/shirkey/.virtualenvs/memex-api/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/Users/shirkey/.virtualenvs/memex-api/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/shirkey/work/sh/darpa/ist-memex-api/api/logs.py", line 41, in post
    response = broker.strip_indices(broker.save(request.DATA))
  File "/Users/shirkey/work/sh/darpa/ist-memex-api/api/logs.py", line 252, in save
    self.backend.put(key, data, doc['indices'], doc['relationships'])
TypeError: put() takes at most 4 arguments (5 given)
```

**Comment by shirk3y** [comment]
#4 should fix it
